[build]
base = "mentoruuniversitypaymentplan"
publish = "mentoruuniversitypaymentplan/"
functions = "mentoruuniversitypaymentplan/payment-page/netlify-functions/"

[build.environment]
STRIPE_PUBLIC_KEY = "${STRIPE_PUBLIC_KEY}"
STRIPE_SECRET_KEY = "${STRIPE_SECRET_KEY}"

