{\rtf1\ansi\ansicpg1252\cocoartf2761
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 [build]\
  base = "mentoruuniversitypaymentplan"\
  publish = "mentoruuniversitypaymentplan"\
  functions = "mentoruuniversitypaymentplan/payment-page/netlify-functions\'94\
  command = "npm run build" \
\
[context.production.environment]\
  STRIPE_PUBLIC_KEY = "pk_live_51P6zKtJxeHdRKz4MDhb9kFoIOG6WDfcLl34bioOKlta4geLCMFRAe42GGrA3W501CbNr8sBsvP0mhStQrJo7qLhs00nnsPL3Jj"\
  STRIPE_SECRET_KEY = "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"\
}